### PR TITLE
tools: Update usage of pyang_plugins

### PR DESCRIPTION
**Pull request by iwaseyusuke**
The current document refers Python Yang package (pyang), but does not explain how to install it.
This patch update to provide an additional explanation for pyang.
Also, this patch updates the format of this document.

Signed-off-by: IWASE Yusuke <iwase.yusuke0@gmail.com>

### CODE REVIEW

**Comment by ishidawataru** [comment]
it would be helpful to add which commit of openconfig we should check out to generate golang config since the latest model doesn't work anymore with the plugin.

https://github.com/openconfig/public/commit/92b36c2adacd2ed16dbd8609419b91bc32556829

I'm checking out this commit, but not sure this is the latest one which we can successfully generate the config.

**Comment by iwaseyusuke** [comment]
@ishidawataru 

Thank you for reviewing my patch!

Yes, I also found this plugin does not work with the latest `openconfig/public`.
So I guess this doc instructs to checkout [`osrg/public`](https://github.com/osrg/public).
With the latest `osrg/public`, this plugin should work.

But...
There are still some error messages.
```
$ PYTHONPATH=. ./bin/pyang --plugindir $GOBGP_PATH/tools/pyang_plugins -p $HOME/yang/standard/ietf/RFC -p $HOME/public/release/models -p $HOME/public/release/models/bgp -p $HOME/public/release/models/policy -f golang $HOME/public/release/models/bgp/openconfig-bgp.yang $HOME/public/release/models/policy/openconfig-routing-policy.yang $GOBGP_PATH/tools/pyang_plugins/gobgp.yang | gofmt > $GOBGP_PATH/config/bgp_configs.go
/home/iwase/public/release/models/bgp/openconfig-bgp.yang:428: error: restriction require-instance not allowed for this base type
/home/iwase/public/release/models/bgp/openconfig-bgp-policy.yang:140: error: restriction require-instance not allowed for this base type
/home/iwase/public/release/models/bgp/openconfig-bgp-policy.yang:163: error: restriction require-instance not allowed for this base type
/home/iwase/public/release/models/bgp/openconfig-bgp-policy.yang:184: error: restriction require-instance not allowed for this base type
/home/iwase/public/release/models/bgp/openconfig-bgp-policy.yang:443: error: restriction require-instance not allowed for this base type
/home/iwase/public/release/models/bgp/openconfig-bgp-policy.yang:492: error: restriction require-instance not allowed for this base type
warning bgp-types:percentage: percentage has already been emitted from openconfig-types:percentage.
```
I guess changing the yang version ("1" -> "1.1") is required to fix this problem, but I don't know whether it is appropriate or not.

**Comment by ishidawataru** [comment]
Oops my bad, I overlooked that the repository used in the script is `osrg/public`.

> but I don't know whether it is appropriate or not.

me neither.

https://github.com/openconfig/public/issues/6

It seems the issue is solved in the latest openconfig model.

**Comment by iwaseyusuke** [comment]
@ishidawataru 
I tried with the commit addressing this issue, but had no luck.
This plugin seems not to work with that commit...

**Comment by fujita** [comment]
Pushed, thanks.
I guess that we'll use the newer openconfig and yang someday. Even with some errors, the current versions work for us so let's use them for now.

**Pull request closed without merging**
