### PR TITLE
Do not install route with originator ID as self in adj-in

### PR DESCRIPTION
**Pull request by mageshgv**
Fixes route loop on softreset

### CODE REVIEW

**Comment by mageshgv** [comment]
While this is a most simple fix for the issue, we do lose track of the received route count. I am not sure if this is alright, if we want to have the route and not accept it, it needs careful handling in multiple cases (softrest, gr, llgr, policy evaluations, table counters etc). @fujita  what do you think is the right solution.

On a different note, it looks like the counters are already broken without this change if I add a second RR here: https://github.com/osrg/gobgp/blob/master/test/scenario_test/route_reflector_test.py#L232 (received, accepted and advertized count in neighbor and also the adj-out display itself with add path is wrong)

**Comment by fujita** [comment]
we should keep such route in adj-in but not send it to the global rib?

**Comment by fujita** [comment]
I'll clean up a way to filter routes in adj-in before the global.

**Comment by fujita** [comment]
I like that the change of aspath option requires the session reset. Then we don't need to reevaluate paths in adj-in on softreset.
https://github.com/osrg/gobgp/pull/2188

**Comment by mageshgv** [comment]
@fujita sorry for the late response. Thanks for the fix #2188 which looks more generic.  Let me close this pr in favor of yours.

**Pull request closed without merging**
