### PR TITLE
Handle ttl-security option correctly

### PR DESCRIPTION
**Pull request by ton31337**
It wasn't configurable at all.

Closes https://github.com/osrg/gobgp/issues/2413

Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>

### CODE REVIEW

**Comment by fujita** [comment]
Thanks! It's a regression during changing the server APIs.

**Comment by ton31337** [comment]
What do you mean?

**Comment by fujita** [comment]
This feature worked long time ago. But it has been broken since the exported APIs of BgpServer was changed.

**Comment by ton31337** [comment]
So, what is the solution then?

**Comment by fujita** [comment]
I've already pushed your fix.

**Comment by ton31337** [comment]
Sorry, I misunderstood you at the beginning.

**Pull request closed without merging**
