### PR TITLE
metrics: add metrics for BGP peer state and number of advertised routes

### PR DESCRIPTION
**Pull request by anitgandhi**

### CODE REVIEW

**Comment by anitgandhi** [comment]
@fujita 👋 hello! We'd really love for this to be in the next release, if possible. When you have a moment, can you please approve the workflow run, and review the changes? Thanks in advance!

**Comment by fujita** [comment]
How prometheus can handle the backward compatibility?

**Comment by anitgandhi** [comment]
I don't think I'm modifying any of the existing metrics, so it shouldn't cause any backwards compatibility issues, I believe.

**Comment by fujita** [comment]
pushed, thanks.

**Pull request closed without merging**
