### PR TITLE
server: Avoid applying policy multiply when updating path

### PR DESCRIPTION
**Pull request by iwaseyusuke**
Currently, UpdatePath() of BgpServer will apply policy multiply, and this causes the unexpected result of policy configurations.

This patch avoids this multiple policy application and fixes an issue which mentioned on this commnet: https://github.com/osrg/gobgp/pull/1252#issuecomment-281984302

Signed-off-by: IWASE Yusuke <iwase.yusuke0@gmail.com>

### CODE REVIEW

**Comment by fujita** [comment]
The current nexthop tracking code modifies paths in zclinet goroutine (that's not the main goroutine). I think that we need to think about how to fix it first.

**Comment by iwaseyusuke** [comment]
Thank you for reviewing my patch.

Would you share me which code modifying paths without main goroutine?
zclient calls `server.UpdatePath` which wrapped with `mgmtOperation` to update nexthop sates;
https://github.com/osrg/gobgp/blob/ce258f05d2fd9c3f66b831cae1e40bc9958cef1f/server/zclient.go#L160-L165
https://github.com/osrg/gobgp/blob/ce258f05d2fd9c3f66b831cae1e40bc9958cef1f/server/server.go#L1320-L1330

**Comment by iwaseyusuke** [comment]
Related to the races of goroutine, I guess the root cause of these problems is that the client side implementation (against `server.BgpServer`), `zclient` and `bmp` for example, can directly access to the resources of `server.BgpServer`.
If these client side implementations are moved from `server` package to `client` package, the resources of `server.BgpServer` should be invisible, and more safely implemented, I guess.

**Comment by fujita** [comment]
Oops, I remember it wrong. Pushed, thanks.

**Pull request closed without merging**
