### PR TITLE
server/zclient: Support basic Nexthop Tracking features

### PR DESCRIPTION
**Pull request by iwaseyusuke**
These patches enable server/zclient to support the basic Nexthop Tracking features:
- registering the interested nexthop using the NEXTHOP_REGISTER messages
- updating the nexthop reachability state based on the NEXTHOP_UPDATE messages from Zebra

Note: The following features are still not implemented yet.
- unregistering the nexthop if no longer required
- calculating "penalty" like Cisco's router when the nexthop state is changed

Test: These patch was tested with the simple case which described on [Quagga's document about Nexthop Tracking](https://github.com/opensourcerouting/quagga/blob/master/doc/next-hop-tracking.txt#L300).

### CODE REVIEW

**Comment by s2ugimot** [comment]
I've tested the branch, seems nexthop tracking is working fine. Great!
But there seems some regression in policy handling.

Here's one simple example I've found: 

With the following policy, it should add **only one** community
```
    Name tag-ixp-neighbors:
        StatementName tag-ixp-neighbors_stmt0:
          Conditions:
            NeighborSet: any ixp-neighbors
          Actions:
             Community:  add[65001:1000]
```

Current master (OK):
```
*>  10.3.0.0/16         10.173.176.103       65003                00:00:21   [{Origin: i} {Med: 0} {Communities: 65001:1000}]
```

With this patch (NG): somehow tripled
```
*>  10.3.0.0/16         10.173.176.103       65003                00:00:11   [{Origin: i} {Med: 0} {Communities: 65001:1000, 65001:1000, 65001:1000}]
```

**Comment by s2ugimot** [comment]
I also found that nexthop tracking only works when I enable RPKI. weird...

**Comment by iwaseyusuke** [comment]
@s2ugimot 
Thank you for testing my branch!

Hummm... it seems to has some problems on the path calculation process...
I found that the best path evaluation runs the multiple times (one becomes from zclient and the others from peer connections) for one NEXTHOP_UPDATE message from Zebra.
Also, Zebra seems to send two NEXTHOP_UPDATE messages (1st one has no nexthop, 2nd has valid nexthops) as the reply for the first NEXTHOP_REGISTER messages from GoBGP.

For RPKI problem, I had no "rpki-servers" setting in "gobgpd.conf" when I tested this branch.
Could you tell me how to reproduce it?

**Comment by s2ugimot** [comment]
@iwaseyusuke Basically I'm using this setup: https://github.com/s2ugimot/gobgp-tutorial
If you have any progress on your branch, I'd love to test at my env :)

Quick config for adding RPKI validation (in yaml):

```yaml
rpki-servers:
  - config:
      address: 210.173.170.254
      port: 323
```

It uses publicly available ROA cache server so all you need is just internet reachability. Really easy. But  I guess at your testing environment it works **without RPKI validation**, right? What I've obserbed is, when I **enable** RPKI validation, nexthop tracking **works** but when I **disable** RPKI validation, nexthop tracking **does not work as expected**.

**Comment by iwaseyusuke** [comment]
@s2ugimot 
Thanks!
Does gobgp-tutorial works with libvirt provider of Vagrant? Only VirtualBox?
Because I've already made Vagrant env with KVM...

For RPKI validation, sorry I could not yet know why this NHT features influence this feature.
I will investigate it.

FYI, I will push WIP branch as "server-zclient-Support_Nexthop_Tracking_wip" to my repository.

**Comment by iwaseyusuke** [comment]
I've updated my patches in order to implement "Dampening of Nexthop tracking" and to add some improvements for calculating the best path.

Also, I did the test as the following.

---
Settings:
- Topology
```
R1: GoBGP
R2: GoBGP + Zebra + OSPFd
R3: Zebra + OSPFd
R4: Zebra + OSPFd

      +----+
      | R3 |... has loopback 10.3.1.1/24
      +----+
       /  |
      /   |
     /   +----+ 
    /    | R4 |
   /     +----+
+----+      |
| R2 |------+
+----+
  | 172.20.12.102/24
  |
  | 172.20.12.0/24
  |
  | 172.20.12.101/24
+----+
| R1 |
+----+
```

- gobgpd.conf on R1:
```toml
[global.config]
  as = 65000
  router-id = "10.0.0.1"

[global.apply-policy.config]
  import-policy-list = [ "tag-ixp-neighbors",]
  default-import-policy = "accept-route"

[[policy-definitions]]
  name = "tag-ixp-neighbors"
  [[policy-definitions.statements]]
    [policy-definitions.statements.conditions.match-neighbor-set]
       match-set-options = "any"
       neighbor-set = "ixp-neighbors"
    [policy-definitions.statements.actions.bgp-actions.set-community]
       options = "add"
    [policy-definitions.statements.actions.bgp-actions.set-community.set-community-method]
       communities-list = [ "65001:1000",]

[defined-sets]
  [[defined-sets.neighbor-sets]]
    neighbor-set-name = "ixp-neighbors"
    neighbor-info-list = [ "172.20.12.102",]

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.20.12.102"
    peer-as = 65000
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv6-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv6-unicast"
```

- gobgpd.conf on R2:
```toml
[global.config]
  as = 65000
  router-id = "10.0.0.2"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.20.12.101"
    peer-as = 65000
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv6-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv6-unicast"

[zebra.config]
  enabled = true
  url = "unix:/var/run/zserv.api"
  redistribute-route-type-list = ["connect"]
  version = 3
```

Procedure:
1. Inject a route to 10.3.1.0/24 into GoBGP on R2. Then, check to receive that route on GoBGP on R1. (The initial Med is "10" in this case.)
```bash
$ gobgp global rib add -a ipv4 10.3.1.0/24 nexthop 10.3.1.1
```
2. Set R2-R3 link down. Then, check Med is updated "10"->"20" at GoBGP both on R1 and R2.
```bash
# On R1:
gobgp global rib -a ipv4
    Network             Next Hop             AS_PATH              Age        Attrs
*>  10.3.1.0/24         10.3.1.1                                  00:00:21   [{Origin: ?} {Med: 20} {LocalPref: 100} {Communities: 65001:1000}]
# On R2:
gobgp global rib -a ipv4
    Network             Next Hop             AS_PATH              Age        Attrs
*>  10.3.1.0/24         10.3.1.1                                  00:00:39   [{Origin: ?} {Med: 20}]
```
3. Set R2-R3 link up. Then, check Med is back to "10" at GoBGP both on R1 and R2.
```bash
gobgp global rib -a ipv4
    Network             Next Hop             AS_PATH              Age        Attrs
*>  10.3.1.0/24         10.3.1.1                                  00:03:50   [{Origin: ?} {Med: 10}]
```

**Comment by fujita** [comment]
Looks fine, thanks a lot!

**Comment by fujita** [comment]
Oops, needs to update the yang file instead of directly modifying the config. I'll take care of it.

**Pull request merged**
