### PR TITLE
support ModGlobalConfig Operation_DEL_ALL

### PR DESCRIPTION
**Pull request by ishidawataru**

### CODE REVIEW

**Comment by ishidawataru** [comment]
test this please

**Comment by shevchenkodenis** [comment]
@ishidawataru I have tested this feature and it works, but not everytime.

Example:
Send REQ_MOD_GLOBAL_CONFIG with Operation_DEL_ALL
```
INFO[0010] Delete a peer configuration for 192.168.30.10 
```
Then I send new local settings by REQ_MOD_GLOBAL_CONFIG with Operation_ADD 
And got this about 1/3 times.        
```
INFO[0010] ReqModGlobalConfigAdd Err: listen tcp4 0.0.0.0:179: bind: address already in use 
ERRO[0010] accept tcp6 [::]:179: use of closed network connection 
ERRO[0010] accept tcp4 0.0.0.0:179: use of closed network connection 
```
Remaining 2/3 times ERRO messages still there, but there are no "listen tcp4 0.0.0.0:179: bind: address already in use" and it correctly configures.

**Comment by ishidawataru** [comment]
@shevchenkodenis Hi. thanks for the report.

Seems `SO_REUSEADDR` is not working (related issue #594).
Could you provide your os and go version info?

I'm using `Linux trusty 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux` and `go1.6`.
the script below is working on my machine.

```shell
#!/bin/sh

for i in `seq 100`
do
   gobgp global as 10 router-id 1.1.1.1
   gobgp global del all
done
```

**Comment by ishidawataru** [comment]
test this please

**Comment by ishidawataru** [comment]
test this please

**Comment by shevchenkodenis** [comment]
@ishidawataru my settings is Linux 4.3.0-1-amd64 #1 SMP Debian 4.3.3-7 (2016-01-19) x86_64 GNU/Linux and I am using go version go1.6 linux/amd64
It's strange but with your script I can't reproduce this bug by CLI commands.
I used this script
```
#!/bin/sh
for i in `seq 100`
do
	./gobgp global as 10 router-id 1.1.1.1
	./gobgp global
	./gobgp global del all
	./gobgp global
done
```
So, error messages like these
```
{"level":"error","msg":"accept tcp6 [::]:179: use of closed network connection","time":"2016-03-17T12:24:53+03:00"}
{"level":"error","msg":"accept tcp4 0.0.0.0:179: use of closed network connection","time":"2016-03-17T12:24:53+03:00"}
```

still appeared on gobgpd side on each "./gobgp global as 10 router-id 1.1.1.1" command , but it seems that settings correctly changed to appropriate values. You can see it in attached logs.
[test-gobgp.log.txt](https://github.com/osrg/gobgp/files/177565/test-gobgp.log.txt)
[gobgpd.log.txt](https://github.com/osrg/gobgp/files/177566/gobgpd.log.txt)

Well, I am still getting "bind address..." error while sending raw grpc messages. But it works good with hack, when I add time.Sleep(time.Second) between DEL_ALL and ADD operations.

What else I can test? Could you merge this into master?

**Comment by shevchenkodenis** [comment]
Thanks a lot!
Let me know how can I be more helpful relating this case.

**Comment by ishidawataru** [comment]
@shevchenkodenis Hi

By [this](https://github.com/osrg/gobgp/commit/9ba923766b93d66785bb410a7e8a68a3c33ee591) commit, you can remove the workaround `time.Sleep(time.Second)`.

Could you check?

**Comment by shevchenkodenis** [comment]
Thanks, @ishidawataru, it works pretty well.

**Pull request merged**
