### PR TITLE
Support Dynamic Neighbor

### PR DESCRIPTION
**Pull request by fujimoto-s**
This patch adds the Dynamic Neighbor feature.
The configuration syntax is like following:
```
[[dynamic-neighbors]]
  [dynamic-neighbors.config]
    prefix = "10.0.0.0/24"
    peer-group = "my-peer-group"
```

(This patch updates #1289)

### CODE REVIEW

**Comment by ishidawataru** [comment]
As we discussed here https://github.com/osrg/gobgp/pull/1289, 
can we add dynamic neighbor configuration in `PeerGroup` instead of
putting new struct `DynamicNeighbor` under `Bgp`?

**Comment by fujimoto-s** [comment]
I think it is possible to add the configuratin in `PeerGroup`.
However, OpenConfig defines `Dynamic Neighbor` using a new struct.
https://github.com/openconfig/public/blob/master/release/models/bgp/openconfig-bgp-global.yang#L129

In #1327, it is said that we will use newer openconfig someday, so I think the configuration structure for Dynamic Neighbor should be similar to OpenConfig's one.

**Comment by ishidawataru** [comment]
I see. then let's keep it as it is.

Can you add some comments in `tools/pyang_plugins/gobgp.yang` that says we are taking the model from the latest openconfig?

**Comment by fujimoto-s** [comment]
Sure, I will write the comment.

**Comment by fujita** [comment]
Pushed, thanks a lot!

**Pull request merged**
