### PR TITLE
Add evpn I-PMSI to proto file

### PR DESCRIPTION
**Pull request by JieJhih**
@fujita I'm using  ```protoc -I api/  --go_out=./api attribute.proto``` command to generate attribute.pb.go , then it have some errors , It make lots of  XXX_Marshal function.

How should I fixed it?
Thanks

### CODE REVIEW

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/BUILD.md

**Comment by JieJhih** [comment]
@fujita Not sure why I still got the problem, can you help me generate the code.
After done, I think it could close the PR.
Thanks

**Comment by fujita** [comment]
You should use an issue instead of a pull request to ask a question.

**Pull request closed without merging**
