### PR TITLE
This Pull proposes CLI to comply with new draft RFC5575bis normalized…

### PR DESCRIPTION
**Pull request by Matt-Texier**
This pull allows to support all the following operators with decimal values used for port, destination ports, source ports, protocol number:

```
            +----+----+----+----------------------------------+
            | lt | gt | eq | Resulting operation              |
            +----+----+----+----------------------------------+
            | 0  | 0  | 0  | true (independent of the value)  |
            | 0  | 0  | 1  | == (equal)                       |
            | 0  | 1  | 0  | > (greater than)                 |
            | 0  | 1  | 1  | >= (greater than or equal)       |
            | 1  | 0  | 0  | < (less than)                    |
            | 1  | 0  | 1  | <= (less than or equal)          |
            | 1  | 1  | 0  | != (not equal value)             |
            | 1  | 1  | 1  | false (independent of the value) |
            +----+----+----+----------------------------------+
```

### CODE REVIEW

**Comment by ishidawataru** [comment]
Tested `parseDecValuesCmd` with follwing inputs.

```go
func Test_ParseDecValuesCmd(t *testing.T) {
  t.Log(parseDecValuesCmd("true", func(int) error { return nil }))
  t.Log(parseDecValuesCmd("100", func(int) error { return nil }))
  t.Log(parseDecValuesCmd("==100", func(int) error { return nil }))
}
```

```bash
$ go test -run ParseDec -v
=== RUN   Test_ParseDecValuesCmd
--- PASS: Test_ParseDecValuesCmd (0.00s)
        bgp_test.go:744: [[128 0]] <nil>
        bgp_test.go:745: [[128 100]] <nil>
        bgp_test.go:746: [[129 100]] <nil>
PASS
```

The result of the second test is expected?
What about setting `==` with bare values? 
Then we don't need to change [here](https://github.com/osrg/gobgp/pull/1258/files#diff-efb83e5a030203af28a46045cb041c16R47)

**Comment by Matt-Texier** [comment]
Hi,

Yep I see ... good catch, there is a BUG here for bare values, 

Agree I'll work on setting `==` as default for bare value.

Working on it today ...

Thanks Matt.

**Comment by ishidawataru** [comment]
https://travis-ci.org/osrg/gobgp/jobs/206091610

Please go fmt.

**Comment by Matt-Texier** [comment]
Sorry for that ...

**Comment by Matt-Texier** [comment]
btw, looks like travis sucks those days :-) !

**Comment by ishidawataru** [comment]
thanks, LGTM.

you can run the same CI for your own forked repository before opening PR as I'm doing.

https://travis-ci.org/ishidawataru/gobgp

**Comment by fujita** [comment]
Thanks, pushed!

**Pull request closed without merging**
