### PR TITLE
policy: add nexthop unchanged

### PR DESCRIPTION
**Pull request by faickermo**
Support config set-next-hop = "unchanged" and also cli command.

Signed-off-by: Faicker Mo <faicker.mo@ucloud.cn>

### CODE REVIEW

**Comment by mrueg** [comment]
@fujita can you take a look at this PR if you have time?

**Comment by fujita** [comment]
The config file also needs to support this feature.

**Comment by faicker** [comment]
@fujita Maybe no need to change the config file. It keeps the same with the `set-next-hop = "self"` usage.

**Comment by fujita** [comment]
Oops, `set-next-hop = "unchanged"` in config file works. Merged, thanks a lot!

**Pull request closed without merging**
