### PR TITLE
When the length is greater than 255 the wrong asnumber will be appended here

### PR DESCRIPTION
**Pull request by chaoliang-wei**

### CODE REVIEW

**Comment by chaoliang-wei** [comment]
Yes When the total is greater than 255 
newAsList := append(asns[:int(repeat)], asList...)
will overwrite asns with the contents of asList starting from repeat；
This PR should be cancelled because it's not quite right for me to change it this way, so if you think this needs to be changed I'll resubmit a PR

**Comment by chaoliang-wei** [comment]
var idx = int(repeat)
			if int(repeat)+len(asList) > 255 {
				idx = int(repeat) - (255 - len(asList))
			}
			newAsList := append(asns[idx:], asList...)
			asPath.Value[0] = bgp.NewAs4PathParam(segType, newAsList)
			asns = asns[:idx]

**Comment by chaoliang-wei** [comment]
Also we want to add del replace to AsPathPrependAction; do you have any comments or suggestions on your side?

**Comment by chaoliang-wei** [comment]
Sorry your previous write up was fine I made a mistake.
repeat is uint8 does not exceed 255, so it will never be overwritten

**Comment by fujita** [comment]
What bug does this fix?

**Comment by fujita** [comment]
Looks like that this doesn't

**Pull request closed without merging**
