### PR TITLE
Fix some issues which broke C library compilation with C++ compiler

### PR DESCRIPTION
**Pull request by pavel-odintsov**
So I'm C++ guy and I have found some compatibility issues with g++. Please review code and merge it. 

Thanks!

### CODE REVIEW

**Comment by h-naoto** [comment]
Can one of the admins verify this path?

**Comment by fujita** [comment]
add to whitelist

**Comment by ishidawataru** [comment]
Hi.
The signature of `free_path()` in the header file and the source file is different.
Could you fix it?

Also `fmt.Println()` can be deleted instead of comment out (my bad..)

**Comment by pavel-odintsov** [comment]
Hello!

Thanks for feedback. Fixed!

**Comment by fujita** [comment]
Squashed and pushed, thanks a lot!

**Pull request closed without merging**
