### PR TITLE
run_all_tests.sh overrides system PAYHONPATH in macosx leads to lib not found

### PR DESCRIPTION
**Pull request by imcom**
preserve current PYTHONPATH when adding the current work dir

add  .vscode / .idea and python tests generated *.xml into gitignore

### CODE REVIEW

**Comment by fujita** [comment]
How you run the script?

**Comment by imcom** [comment]
I have run the script in macosx, and it failed due to libs could not be found

**Comment by imcom** [comment]
btw, a minor issue with the doc , `gobgp` cli does not support MTR dump

**Comment by fujita** [comment]
> I have run the script in macosx, and it failed due to libs could not be found
Understood, simply you can't execute the script.
Passing the variable every time executing python looks verbose. How about the following?
https://github.com/osrg/gobgp/pull/1524

**Comment by imcom** [comment]
I vote for your modification therefore I will close this PR

**Comment by fujita** [comment]
@imcom Thanks, pushed https://github.com/osrg/gobgp/pull/1524
Feel free to create a new pr to add some files to .gitignore.

**Pull request closed without merging**
