### PR TITLE
Bump dependencies / Release with go 1.17

### PR DESCRIPTION
**Pull request by mrueg**
This updates dependencies and builds the binaries with go 1.17.
Happy to update further, if we are okay with breaking compatibility with go <=1.16.

```
github.com/osrg/gobgp/v3/cmd/gobgp tested by
        github.com/osrg/gobgp/v3/cmd/gobgp.test imports
        github.com/stretchr/testify/assert imports
        gopkg.in/yaml.v3 tested by
        gopkg.in/yaml.v3.test imports
        gopkg.in/check.v1 loaded from gopkg.in/check.v1@v1.0.0-20180628173108-788fd7840127,
        but go 1.16 would select v1.0.0-20190902080502-41f04d3bba15

To upgrade to the versions selected by go 1.16:
        go mod tidy -go=1.16 && go mod tidy -go=1.17
If reproducibility with go 1.16 is not needed:
        go mod tidy -compat=1.17
For other options, see:
        https://golang.org/doc/modules/pruning
```

### CODE REVIEW

**Comment by fujita** [comment]
Any specific reasons for updating dependencies?

**Comment by jauderho** [comment]
FWIW, now that Go 1.18 has been released, Go 1.16 is no longer considered supported. @mrueg This should be rebased to Go 1.18 if you are going through the effort of updating things.

https://endoflife.date/go

**Comment by fujita** [comment]
You can build the current code with Go 1.18. What's the point of breaking compatibility with old go versions?

**Comment by mrueg** [comment]
> Any specific reasons for updating dependencies?
* go-systemd was old (2019) and not using the versioned module
* viper/cobra vendoring a vulnerable lib https://github.com/spf13/cobra/issues/1538
* go 1.18 being released and thus go 1.16 being EOL (thus switching to go 1.17 but still allowing folks to build with go >=1.15)

**Comment by fujita** [comment]
Sounds reasonable. Pushed, thanks!

**Pull request closed without merging**
