### PR TITLE
table/message: Merge withdrawn routes in Update message

### LINKED ISSUE #1309: Withdraw grouping chaotic
Withdraw update messages aren't grouped even when its possible, some withdraws messages are 1 per packet and others are 2-3 or maximum per packet.

My test was just adding 1000 routes and then purge them all with `gobgp global rib del all -a ipv4` all routes are same except prefix, with prefix length /32

### PR DESCRIPTION
**Pull request by fujimoto-s**
RFC4271 allows to merge withdrawn routes in one update message.
This resolves #1309.

Signed-off-by: Satoshi Fujimoto <satoshi.fujimoto7@gmail.com>

### CODE REVIEW

**Comment by fujita** [comment]
Withdraw message doesn't have any attributes so the comparison is pointless. I think that the code to merge messages needs to be refactored.

**Comment by fujimoto-s** [comment]
I updated my patch.
I removed attribute comparison for withdraw messages, and refactored the code for readability.

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/pull/1505

I refactored the code throughout.

**Comment by fujita** [comment]
Pushed https://github.com/osrg/gobgp/pull/1505

**Pull request closed without merging**
