### PR TITLE
Add BGP-LS SRLG support

### PR DESCRIPTION
**Pull request by tomjshine**
Added support for the SRLG BGP-LS attribute TLV. This is my first time writing go, so let please let me know if I'm doing anything silly. Happy to amend as you see fit ;). Let me know if you need any more info.

### CODE REVIEW

**Comment by tomjshine** [comment]
Junos "show route lsdist.0"
```
LINK { Local { ISO:0001.0000.0001.00 }.{ IPv4:10.0.0.0 } Remote { ISO:0001.0000.0002.00 }.{ IPv4:10.0.0.1 } ISIS-L2:0 }/1152 (1 entry, 0 announced)
        *IS-IS  Preference: 18
                Level: 2
                Next hop type: Fictitious, Next hop index: 0
                Address: 0xa1d9dbc
                Next-hop reference count: 8
                Next hop:
                State: <Active NotInstall>
                Age: 7:19:02
                Validation State: unverified
                Task: IS-IS
                AS path: I
                Color: 1024
                Maximum bandwidth: 1000Mbps
                Reservable bandwidth: 1000Mbps
                Unreserved bandwidth by priority:
                  0   1000Mbps
                  1   1000Mbps
                  2   1000Mbps
                  3   1000Mbps
                  4   1000Mbps
                  5   1000Mbps
                  6   1000Mbps
                  7   1000Mbps
                Metric: 10
                TE Metric: 30
                SRLG membership:
                  ten(0xa)
                  twenty(0x14)

```

**Comment by tomjshine** [comment]
Output:
```
link {
  admin_group: 1024
  default_te_metric: 30
  igp_metric: 10
  bandwidth: 125000000.0
  reservable_bandwidth: 125000000.0
  unreserved_bandwidth: 125000000.0
  unreserved_bandwidth: 125000000.0
  unreserved_bandwidth: 125000000.0
  unreserved_bandwidth: 125000000.0
  unreserved_bandwidth: 125000000.0
  unreserved_bandwidth: 125000000.0
  unreserved_bandwidth: 125000000.0
  unreserved_bandwidth: 125000000.0
  srlgs: 10
  srlgs: 20
}

```

**Comment by fujita** [comment]
thanks for the pull request.

1. please fix the staticcheck error:
https://travis-ci.org/github/osrg/gobgp/jobs/678410012
2. please rebase on the latest master. I pushed the fix for the change of docker package url.

**Comment by tomjshine** [comment]
Ok. done and done ;)

Took a couple of attempts but all tests seem to be passing now. Please let me know if there is anything else.

**Comment by fujita** [comment]
pushed, thanks!

**Comment by zhanggongc** [comment]
> show rout
"show route lsdist.0" where this command  come from ? how to detonate bgp-ls  ?

**Pull request merged**
