### PR TITLE
Do not supress initial non-established peer state in MonitorPeer

### LINKED ISSUE #2047: Feature Request: don't suppress initial non-established peer state in MonitorPeer
MonitorPeerRequest w/current=true does not return the current state unless it is established. https://github.com/osrg/gobgp/blob/ccdc2e6277020e571da7792c1d9e76cf13e82f44/pkg/server/server.go#L4013-L4023

### PR DESCRIPTION
**Pull request by ecbaldwin**
The issue with the initial update seemed to be that sometimes the
connection has not yet been established. Trying to get the remote and
local connection data caused a segmentation violation because
`fsm.conn` was nil.

Initial testing seems ok but I have not yet run the full suite of tests.

fixes #2047

### CODE REVIEW

**Comment by fujita** [comment]
I think that we should not change the MonitorPeer API behavior without the major version updated. Adding a new option to MonitorPeerRequest or something else?

**Comment by ecbaldwin** [comment]
ok, that is fair. I'll update this with an additional to the MonitorPeerRequest which will enable this behavior.

**Comment by fujita** [comment]
Thanks. I've just remembered the following issue then I'm inclining to add a new API to just send all peer states and meet the requirement of the following instead of adding options to the current API.
https://github.com/osrg/gobgp/issues/2046

**Comment by fujita** [comment]
https://github.com/fujita/gobgp/tree/monitor-event

You get all the changes of peer state. If you don't need some, just ignore. The feedback is greatly appreciated.

**Comment by fujita** [comment]
thanks

**Pull request merged**
