### PR TITLE
Make generated BGP configuration code public

### PR DESCRIPTION
**Pull request by wenovus**
Move internal/pkg/config -> pkg/bgpconfig

Please advise if there are internal stuff here and I can try to figure out if I can move them back to internal.

Background: https://github.com/osrg/gobgp/issues/2593

### CODE REVIEW

**Comment by fujita** [comment]
Why simply moving to `pkg/config`?

**Comment by wenovus** [comment]
> Why simply moving to `pkg/config`?

Two reasons:
One is to avoid taking away "config" as a variable name.

https://go.dev/blog/package-names
```
Don’t steal good names from the user. Avoid giving a package a name that is commonly used in client code. For example, the buffered I/O package is called bufio, not buf, since buf is a good variable name for a buffer.
```

Another reason is "config" is a [generic name](https://pkg.go.dev/search?q=config), so for example if I'm writing a virtual router with configuration from different protocols "config" doesn't really tell me which one I'm working with, making the code harder to read.

**Comment by wenovus** [comment]
> I don't think `config` is a good variable name.
> 
> > Another reason is "config" is a [generic name](https://pkg.go.dev/search?q=config), so for example if I'm writing a virtual router with configuration from different protocols "config" doesn't really tell me which one I'm working with, making the code harder to read.
> 
> You can't import a package as a different name?
> 
> I don't think using `bgp` prefix for gobgp packages is a good idea. Just verbose.

I see, that's reasonable. However, when I merge these packages I run into a dependency cycle:
package github.com/osrg/gobgp/v3/cmd/gobgp                                                                                                         
        imports github.com/osrg/gobgp/v3/internal/pkg/table                                                                                        
        imports github.com/osrg/gobgp/v3/pkg/config                                                                                                
        imports github.com/osrg/gobgp/v3/internal/pkg/table: import cycle not allowed                                                              

This is because "table" now imports types from "config" (aka. "bgconfig"), which in turn imports from the table package.
```
table/destination.go
31:var SelectionOptions config.RouteSelectionOptionsConfig
32:var UseMultiplePaths config.UseMultiplePathsConfig
121:func NewPeerInfo(g *config.Global, p *config.Neighbor) *PeerInfo {
```

When I moved policy.go out into its own package to avoid "config" importing "table", I now see
package github.com/osrg/gobgp/v3/internal/pkg/table                                                                                                                                                                                                                                                   
        imports github.com/osrg/gobgp/v3/pkg/config                                                                                                
        imports github.com/osrg/gobgp/v3/pkg/server                                                                                                
        imports github.com/osrg/gobgp/v3/internal/pkg/table: import cycle not allowed                                                              

This is because the original "config" refers to server.BgpServer, and "server" in turn imports from the internal "table" package other than policy.go

```
server/rpki.go     
62:     table     *table.ROATable                                       
66:func newROAManager(table *table.ROATable, logger log.Logger) *roaManager {
101:    m.table.DeleteAll(host)
```

What do you think is an appropriate solution?

**Comment by wenovus** [comment]
Hi, a couple ideas here to solve the dependency issue:
1. The current `config` package is not about GoBGP's configuration schema, but rather about applying the configuration on an existing GoBGP server. So, we can justify calling the `internal/pkg/config` package `pkg/schema` instead of merging it with the existing `pkg/config` to make it clear that this is about the configuration schema rather than configuration operations. In this way we also avoid the dependency cycle.
2. We can directly break the dependency cycle by creating an interface for `server.BgpServer`'s methods and have `pkg/config` call its functions instead of referring to the `server.BgpServer` struct directly.

**Pull request closed without merging**
