### PR TITLE
Use critbit instead of go-radix

### PR DESCRIPTION
**Pull request by fujimoto-s**
As discussed in #1414, critbitgo reduces memory consumption and give some speedups.
This PR replaces go-radix with critbitgo.

### CODE REVIEW

**Comment by brotherdust** [comment]
@fujimoto-s Is there a chance this will ever be merged? It's been here a while.

**Comment by fujita** [comment]
@brotherdust I've been working on this. I pushed the necessary feature to the upstream
https://github.com/k-sone/critbitgo/commit/9c279c04d45ea42adc9a3a60cf945ddd8b99105e

I plan to finish this after the next release.

**Comment by brotherdust** [comment]
@fujita Neat! Thank you for your quick response!

**Comment by fujita** [comment]
Done. go-radix usage has gone. I did in a slightly different way. But this pr gives me lots of useful info, thanks a lot for @fujimoto-s !

I use critbitgo's Net APIs:
https://github.com/k-sone/critbitgo/blob/master/net.go

These are implemented on the top of cribitgo APIs, handy for network code. For example, Net APIs use net.IPNet as an argument while cribitgo APIs use []byte.

**Pull request closed without merging**
