### PR TITLE
flowspec: correct place for & bit in opflags

### PR DESCRIPTION
**Pull request by shevchenkodenis**
Issue #1322

### CODE REVIEW

**Comment by shevchenkodenis** [comment]
According to python tests exabgp doesn't broke connection on wrong fields in flowspec packets, but my Juniper does. Because of this and also because of checking local rib, but not rib of neighbor, tests pass.

**Comment by ishidawataru** [comment]
@shevchenkodenis Thanks for the fix.

We also need to fix the formatting.
Could you do that?

```
$ gobgp global rib -a ipv4-flowspec add match protocol tcp destination-port '==80' '>=8080&<=8888' then discard
$ gobgp g ri -a ipv4-flowspec
    Network                                                Next Hop             AS_PATH              Age        Attrs
*>  [protocol:==tcp ][destination-port:==80 >=8080 <=8888&]fictitious                                00:00:05   [{Origin: ?} {Extcomms: [discard]}]
```

**Comment by shevchenkodenis** [comment]
@ishidawataru what is wrong with formatting?

**Comment by ishidawataru** [comment]
'>=8080 <=8888&' should be '>=8080&<=8888' ?

**Comment by shevchenkodenis** [comment]
Oh, yeah! I'll try to fix it.

**Comment by ishidawataru** [comment]
@shevchenkodenis thanks. I did several tests and found the rule below doesn't get accepted with your commits. Could you look into it?

```
$ gobgp g ri add -a ipv4-flowspec match port '!=10&!=20&!=30' then discard
err: AND or OR (space) operator appears multiple time
usage: global rib add match <MATCH_EXPR> then <THEN_EXPR> -a ipv4-flowspec
   <MATCH_EXPR> : { destination <PREFIX> [<OFFSET>] | source <PREFIX> [<OFFSET>] |
                    protocol <PROTO>... | fragment <FRAGMENT_TYPE> | tcp-flags [!] [=] <TCPFLAG>... |
                    { port | destination-port | source-port | icmp-type | icmp-code | packet-length | dscp | label } <ITEM>... }...
   <PROTO> : tcp, sctp, icmp, igmp, udp, gre, ospf, ipip, pim, igp, rsvp, unknown, egp, <VALUE>
   <FRAGMENT_TYPE> : dont-fragment, is-fragment, first-fragment, last-fragment, not-a-fragment
   <TCPFLAG> : F, S, R, P, U, C, E, A
   <ITEM> : & {<|<=|>|>=|==|!=}<value>
   <THEN_EXPR> : { accept | discard | rate-limit <value> | redirect <RT> | mark <value> | action { sample | terminal | sample-terminal } | rt <RT>... }...
   <RT> : xxx:yyy, xx.xx.xx.xx:yyy, xxx.xxx:yyy
```

**Comment by shevchenkodenis** [comment]
@ishidawataru I already noticed it and, for the first look, it seems that this commit 55e96842593e9645ea0866398d57cfa8a8530385 also limits number of elements to 2. I will fix it and add correlated test.

**Comment by fujita** [comment]
Pushed, thanks!

**Pull request closed without merging**
