### PR TITLE
allows to configure a local address for each bgp session

### PR DESCRIPTION
**Pull request by tamihiro**
iBGP sessions are in most cases initiated with a loopback address of each router.
This patch allows to configure a specific LocalAddress in each Neighbors.NeighborList.NeighborConfig stanza, which to be used in connect() function.

### CODE REVIEW

**Comment by h-naoto** [comment]
Can one of the admins verify this path?

**Comment by ishidawataru** [comment]
Hello @tamihiro 

Thank you for the PR!

Could you use https://github.com/osrg/gobgp/blob/master/config/bgp_configs.go#L527 instead of https://github.com/osrg/gobgp/pull/314/files#diff-b4479553130fb5ef91581f2f08da5ca8R723 ?

Since `bgp_configs.go` is generated from OpenConfig yang model by this tool (https://github.com/osrg/gobgp/tree/master/tools/pyang_plugins), we must avoid
modifying `bgp_configs.go` directly.

**Comment by fujita** [comment]
add to whitelist

**Comment by tamihiro** [comment]
My apologies... should have taken a better look at the relevant code before submitting a request.
I'll submit another request shortly after revoking this one.

**Pull request closed without merging**
