### PR TITLE
proposing a split function for use with bufio

### PR DESCRIPTION
**Pull request by ramrunner**
This split function allows the use of bufio.Scanner to read a set of MRT messages. are you guys ok?

### CODE REVIEW

**Comment by h-naoto** [comment]
Can one of the admins verify this path?

**Comment by yokoi-h** [comment]
add to whitelist

**Comment by fujita** [comment]
Looks like a nice addition. Pushed, thanks!
My trivial comment is that always using len(data) might be better than using cap() too.

**Comment by ramrunner** [comment]
thanks fujita! your comment is true. will keep it in mind for future usage!
thanks again guys.

**Pull request closed without merging**
