### PR TITLE
api: Define protobuf structures of BGP NLRI and Path Attributes

### PR DESCRIPTION
**Pull request by iwaseyusuke**
Currently, the gRPC client need to serialize the NLRI and Path Attributes into bytes representation when calling AddPath gRPC API, but this requires the client side applications have the implementation to encode/decode the BGP attributes. Then it can be difficult to implement gRPC client with the languages other than Go.

This PR defines the protobuf structures of BGP NLRI and Path Attributes and enable to call AddPath API with these structures.

For the discussion about this improvements and sample code of gRPC client written in Python, see https://github.com/osrg/gobgp/issues/1457.

### CODE REVIEW

**Comment by fujita** [comment]
Great, can you add some tests of grpc with this new API? I'm thinking about using gogo/protobuf but concern of Any type a bit.

**Comment by cstockton** [comment]
I think this change would be great. One thing to consider would be taking this opportunity to remove the `table` importing of `api`. This is because it forces anyone who wants to use the `api` to download all of the packages the sever requires, which is a lot of dependencies. If more functions like `ToPathApiInBin` are added to the `api` package now it will make migrating away more difficult in the future. The change itself would be fairly simple, remove ToNativePath and add `table.PathToAPI()` `table.APIToPath()` (or whatever names are preferred). Then in the future other dependencies could slowly be peeled away, which I would be happy to help with if the GoBGP authors would accept the change.

**Comment by fujita** [comment]
I guess that we are on the same page. Once I push this pr, I want to make api/ include only code to access to the gRPC APIs and handy functions to handle the protobuf structures. That should remove lots of dependencies. I want to move grpc_server.go and util.go to somewhere else. Then I want to remove client/ and rewrite gobgp/*.go to use only api/.

**Comment by iwaseyusuke** [comment]
I've updated to move `api/bgp/attribute*` into `api/` to build protobuf by single `protoc` command. (Also reworded a commit tile, sorry for disturbing)

**Comment by fujita** [comment]
Thanks a lot, pushed. I think that it's better to remove the usage of logrus and just return an error. I'll take care of such minor issues.

**Pull request merged**
