### PR TITLE
zebra: supporting FRRouting version 7

### PR DESCRIPTION
**Pull request by irino**
- the "version" parameter (which means ZAPI) 6 in zebra config changes supporting FRRouting version 7 instead of FRRouting version 6.
 - the "software-name" parameter which supports backward compatibility is added in zebra config.
   (GoBGP support FRRouting version 6 when "version = 6" and "software-name = frr6" is configured.)

### CODE REVIEW

**Comment by irino** [comment]
The Travis CI error output is "go: github.com/kr/pretty@v0.0.0-20160823170715-cfb55aafdaf3: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/33119c1bd11a6422692760af70c33923f3c3f3c4373f6e1d9f93bed6ae1e1c89: exit status 128:
	fatal: unable to access 'https://github.com/kr/pretty/': gnutls_handshake() failed: A TLS packet with unexpected length was received.".
I assume this error is caused by CI's environment problem.

**Comment by irino** [comment]
I updated documents only, however, CI fails on unit tests whom the previous commit passes.

**Comment by fujita** [comment]
@irino temporary failure of travis-ci or you actually fixed something?

**Comment by irino** [comment]
@fujita I met temporary failures of CI on commit 89aa791 and  b6f5c87. Finally, I updated my source code which does not relate for temporary failures of CI.
On commit 2b3a70f, I met error by staticcheck. It is my failure.
On commit 89aa791, I fixed my code for passing staticcheck, however, I met a temporary failure of CI.
On commit b6f5c87 and 7a76eac, I updated a document and I met a temporary failure of CI.
On commit a0f4119, I updated zclient_test and I found and fix a bug of commit 2b3a70f. Finally, I passed CI fortunately on this commit.

**Comment by fujita** [comment]
I'm not sure if I understand why software-name stuff is necessary.
Both frr v6 and v7 use zapi v6 but frr v6's zapi v6 is not compatible with frr v7's zapi v6, right?

**Comment by irino** [comment]
Yes. you are right.

**Comment by fujita** [comment]
insane. I'll squash the commits and push. Thanks a lot!
hopefully, we could use software to manage various data planes with the sane API like grpc someday.

**Pull request closed without merging**
