### PR TITLE
Introduce a common label for containers and networks created in gobgp tests

### PR DESCRIPTION
**Pull request by imcom**
use a common prefix for containers for easy cleaning up;
use label for networks in order to avoid colliding with others

### CODE REVIEW

**Comment by iwaseyusuke** [comment]
Hi @imcom 
Looks good to me, thanks!
I think this change is very good idea!

Just wondering, how about using "--label" to run container at the following?
https://github.com/osrg/gobgp/blob/9da6e7c3a25cfaa1f33ed5ddcc0ad1699c430e17/test/lib/base.py#L211-L216

If adding label to container instances, I guess we can filter target containers without renaming.

**Comment by imcom** [comment]
yea, sure. How come I missed that label filtering in `docker ps`, let me use label for filtering in containers instead

**Comment by iwaseyusuke** [comment]
Great! Thanks!

**Comment by fujita** [comment]
Squashed #2 and #3, pushed, thanks!

**Pull request closed without merging**
