### PR TITLE
api: Support mp-graceful-restart config in AddNeighbor

### PR DESCRIPTION
**Pull request by iwaseyusuke**
This patch extends GracefulRestart message structure in AddNeighbor API to configure "mp-graceful-restart.config".

Also, this patch includes an improvement for reducing for loop against "config.Neighbor.AfiSafis".

fixes https://github.com/osrg/gobgp/issues/1356

Signed-off-by: IWASE Yusuke <iwase.yusuke0@gmail.com>

### CODE REVIEW

**Comment by fujita** [comment]
How about LongLivedGracefulRestart parameters per AfiSafi?

**Comment by iwaseyusuke** [comment]
Thank you for pointing out.
For `LongLivedGracefulRestart`, in addition to a parameter for `enabled` or not, we need to a parameter for `restart-time`.
I will update to add a new message structure `LongLivedGracefulRestart` into `api/gobgp.proto`.

**Comment by fujita** [comment]
Better to be consistent with openconfig model? Adding the list of a structure like FamilyInfo (or something better) to Peer structure. FamilyInfo includes gracefull restart parameters.

**Comment by iwaseyusuke** [comment]
Yes, I think it is better and I tried to do so at first.
But I found Peer structure already has

**Comment by iwaseyusuke** [comment]
Yes, I think it is better and I tried to do so at first.
But I found Peer structure already has [`repeated uint32 families = 1;`](https://github.com/osrg/gobgp/blob/83684d5e62fb14596aabf03747a8b395543f91bb/api/gobgp.proto#L547), I stopped to do it.
If consistency with OpenConfig is more reasonable, I will update my PR.

**Comment by iwaseyusuke** [comment]
Sorry, I missed to delete this branch.
I will re-open another PR.

**Pull request closed without merging**
