### PR TITLE
bugfix: fix the issue of overriding bgp attrs due to mp_reach_nlri is unchanged per policy

### PR DESCRIPTION
**Pull request by imcom**
This addresses the issue https://github.com/osrg/gobgp/issues/2422

### CODE REVIEW

**Comment by imcom** [comment]
oh, I will fix the tests asap

**Comment by fujita** [comment]
using packerMP instead of packerV4 is simpler? I guess that we really need to clean up the code though.

**Comment by imcom** [comment]
Indeed, but it does not cover all scenarios. First of all, we could not know for sure when to use packerMP if both NLRI and next-hop are IPv4 UC, the difference maker is policy but whether an impactful policy is applied is now known when choosing a packer. Secondly, if GoBGP sits in between two peers where one peer supports MP capability and the other one does not, it would not work if using packerMP. Feel free to correct me if I got it wrong. Thanks in advance.

**Comment by imcom** [comment]
There are certain cases that have to use MP:
1) NLRI is not IPv4_UC
2) NLRI is IPv4_UC but next hop is IPv6

However, in our production environment, we do see just a few routers announce IPv4 + IPv4 via MP_REACH_NLRI

**Comment by imcom** [comment]
This static check does not look like related to this pull request , could be golang tool upgrade ?

**Comment by imcom** [comment]
better remove MP_REACH_NLRI directly, will open another pull request

**Pull request closed without merging**
