### PR TITLE
Vrf route to zebra patch

### PR DESCRIPTION
**Pull request by amanshaikh75**
This request is to merge changes related to communicating VRF routes to FRR/Zebra. I have changed the source-code to pass VRF-ID while passing the route to FRR/Zebra. Can this change be merged into the master branch?

thanks,
aman (AT&T Research)

### CODE REVIEW

**Comment by iwaseyusuke** [comment]
Hi @amanshaikh75

Great! Thank you for your PR!
May I have some comments on your patches?

- Please apply `go fmt` before committing your changes.
  `go fmt $(go list ./... | grep -v '/vendor/')` command is very convenient to keep go files clean.
- To avoid goroutine races, we should avoid calling the APIs of `TableManager` from `zclient`. Please consider to use the APIs of `BgpServer`.
  For example, the following is equivalent to your patches? (some changes by `go imports` command are included though...)

```diff
diff --git a/server/zclient.go b/server/zclient.go
index 46cab1a..de6eaf1 100644
--- a/server/zclient.go
+++ b/server/zclient.go
@@ -17,15 +17,17 @@ package server

 import (
        "fmt"
-       "github.com/osrg/gobgp/packet/bgp"
-       "github.com/osrg/gobgp/table"
-       "github.com/osrg/gobgp/zebra"
-       log "github.com/sirupsen/logrus"
        "net"
        "strconv"
        "strings"
        "syscall"
        "time"
+
+       log "github.com/sirupsen/logrus"
+
+       "github.com/osrg/gobgp/packet/bgp"
+       "github.com/osrg/gobgp/table"
+       "github.com/osrg/gobgp/zebra"
 )

 type pathList []*table.Path
@@ -504,7 +506,13 @@ func (z *zebraClient) loop() {
                                }
                        case *WatchEventUpdate:
                                if body, isWithdraw := newNexthopRegisterBody(msg.PathList, z.nhtManager); body != nil {
-                                       z.client.SendNexthopRegister(0, body, isWithdraw)
+                                       vrfID := uint16(0)
+                                       for _, vrf := range z.server.GetVrf() {
+                                               if vrf.Name == msg.Neighbor.Config.Vrf {
+                                                       vrfID = uint16(vrf.Id)
+                                               }
+                                       }
+                                       z.client.SendNexthopRegister(vrfID, body, isWithdraw)
                                }
                        }
                }
```

**Comment by amanshaikh75** [comment]
Hi @iwaseyusuke 

Your suggestion looks fine to me. Will you apply your patch to the code repository? Or should I update my pull request?

Your comment about using 'go fmt' is duly noted. Thanks for pointing that out to me as I am relatively a newbie to GoLang.

aman

**Comment by iwaseyusuke** [comment]
@amanshaikh75

**Comment by iwaseyusuke** [comment]
Thanks @amanshaikh75 

Either is fine. If I will create another PR, I guess I need to know the above changes are enough to communicate VRF routes on FRR/Zebra.
I'm sorry I don't yet understand what we need to implement to work with VRFs on FRR/Zebra.
Is there any other requirement to achieve to it? This PR is the first step for it?

**Comment by amanshaikh75** [comment]
I will test the fix you proposed, and then open another pull request.

I don't understand GoBGP code well enough to say whether this change is sufficient to communicate VRF routes to FRR/Zebra. In my testing so far, things have worked, but I don't know if it will work in every corner-case.

**Comment by amanshaikh75** [comment]
Hi @iwaseyusuke 

I have submitted a new PR: https://github.com/osrg/gobgp/pull/1572

aman

**Comment by iwaseyusuke** [comment]
@amanshaikh75 

Thank you for updating your patches!

>I don't understand GoBGP code well enough to say whether this change is sufficient to communicate VRF routes to FRR/Zebra. In my testing so far, things have worked, but I don't know if it will work in every corner-case.

I see.
Hmmm... I guess we may have to understand Zebra protocol model if we need to use more FRR/Zebra's features...

**Pull request closed without merging**
