### PR TITLE
mrt: Use copy of MrtConfig to avoid data race

### PR DESCRIPTION
**Pull request by iwaseyusuke**
Because MrtConfig is passed as pointer value, configuration can be overwritten by caller, then if multiple configurations for MRT dump, only last one is enable and the others are not enabled.

This patch fixes to create copy of MrtConfig and avoids this problem.

Fixes https://github.com/osrg/gobgp/issues/1469

### CODE REVIEW

**Comment by a16** [comment]
Confirmed #1469 would be fixed.

**Comment by fujita** [comment]
Hmm, I think that it's a caller problem. I thought that we fixed the similar bug and looks like we still have the same bugs.
https://github.com/osrg/gobgp/pull/1477

I guess that these functions had better to take a copy not a pointer.

**Comment by iwaseyusuke** [comment]
Thank you for reviewing my patch.

I agree taking a copy instead of a pointer is better.

But... functions of BgpServer (e.g, EnableMrt) is exported function, I don't think it better to require callers to take care of it.

How about change type of argument at non-exported function?
```diff
diff --git a/server/mrt.go b/server/mrt.go
index fe61f7a..e7ea21b 100644
--- a/server/mrt.go
+++ b/server/mrt.go
@@ -338,7 +338,7 @@ type mrtManager struct {
        writer    map[string]*mrtWriter
 }
 
-func (m *mrtManager) enable(c *config.MrtConfig) error {
+func (m *mrtManager) enable(c config.MrtConfig) error {
        if _, ok := m.writer[c.FileName]; ok {
                return fmt.Errorf("%s already exists", c.FileName)
        }
@@ -377,7 +377,7 @@ func (m *mrtManager) enable(c *config.MrtConfig) error {
                setRotationMin()
        }
 
-       w, err := newMrtWriter(m.bgpServer, c, rInterval, dInterval)
+       w, err := newMrtWriter(m.bgpServer, &c, rInterval, dInterval)
        if err == nil {
                m.writer[c.FileName] = w
        }
diff --git a/server/server.go b/server/server.go
index 03b9cbd..3843729 100644
--- a/server/server.go
+++ b/server/server.go
@@ -2272,7 +2272,7 @@ func (s *BgpServer) ReplacePolicyAssignment(name string, dir table.PolicyDirecti
 
 func (s *BgpServer) EnableMrt(c *config.MrtConfig) error {
        return s.mgmtOperation(func() error {
-               return s.mrtManager.enable(c)
+               return s.mrtManager.enable(*c)
        }, false)
 }
 ```

The same can be applied for RPKI and BMP, I guess.

**Comment by fujita** [comment]
You say,  the majority of exported functions like AddNeighbor needs to be updated in the same way?

**Comment by fujita** [comment]
I've pushed the fix (because we got a bug report). Let's discuss the better API on a new issue.

**Comment by iwaseyusuke** [comment]
Hmmm... Yes.

Many of exported functions has pairs of non-exported version function (in case of AddNeighbor, addNeighbor is that one).
If we fix this problem in the mentioned way, we need to change non-exported version of them...

**Pull request closed without merging**
