### PR TITLE
config: add-paths structure per AFI-SAFI

### PR DESCRIPTION
**Pull request by iwaseyusuke**
This PR introduces "add-paths" structure per AFI-SAFI in order to configure add-paths features per AFI-SAFI.

### CODE REVIEW

**Comment by fujita** [comment]
The latest openconfig supports this feature?

**Comment by iwaseyusuke** [comment]
Yes, the latest openconfig has `add-paths` container per `afi-safi`.

In `afi-safi` list difinition;
https://github.com/openconfig/public/blob/0121879afbc22df19541c031c4e9482d8d6c4cd7/release/models/bgp/openconfig-bgp-global.yang#L286

Definition of `bgp-common-structure-neighbor-group-add-paths`;
https://github.com/openconfig/public/blob/0121879afbc22df19541c031c4e9482d8d6c4cd7/release/models/bgp/openconfig-bgp-common-structure.yang#L156-L177

Definition of `bgp-common-neighbor-group-add-paths-config`;
https://github.com/openconfig/public/blob/0121879afbc22df19541c031c4e9482d8d6c4cd7/release/models/bgp/openconfig-bgp-common.yang#L334-L377

FYI, the latest openconfig has also `send bool` and `eligible-prefix-policy` fields in `add-paths` structure.

**Comment by iwaseyusuke** [comment]
I've updated PR for resolving conflict of `api/gobgp.pb.go`.

**Comment by fujita** [comment]
Pushed, thanks!

**Pull request closed without merging**
