### PR TITLE
test: Test for Graceful Restart with multiple peers

### PR DESCRIPTION
**Pull request by fujimoto-s**
This patch adds tests for graceful restart with multiple peers (to cover bugs like #1296).

Signed-off-by: Satoshi Fujimoto <satoshi.fujimoto7@gmail.com>

### CODE REVIEW

**Comment by fujita** [comment]
Why not adding this to https://github.com/osrg/gobgp/blob/master/test/scenario_test/graceful_restart_test.py

**Comment by fujimoto-s** [comment]
Sorry, there is no reason to divide this test class.
I will update it.

**Comment by fujita** [comment]
Pushed, thanks!
A easy way to reproduce a race condition of https://github.com/osrg/gobgp/issues/1296 ?

**Comment by fujimoto-s** [comment]
Without this patch, #1296 is reproduced unless the restarting speaker connects to its helpers at exactly the same time, but it rarely happens.
So, I think we can reproduce #1296 in one or two trials.

**Pull request merged**
