### PR TITLE
pkg/packet/bgp: fix Type 2 ST route JSON format

### PR DESCRIPTION
**Pull request by higebu**

### CODE REVIEW

**Comment by higebu** [comment]
@fujita I think the `ci/router` failed due to GitHub Actions problem. Please re-run the `ci/router`.

**Comment by fujita** [comment]
pushed, thanks.

**Comment by higebu** [comment]
Thanks!

**Comment by higebu** [comment]
BTW, GoBGP successfully passed the BGP-MUP SAFI interoperability tests alongside other implementations during the IETF 116 Hackathon.
https://ietf-hackathon.github.io/ietf116-project-presentations/ietf-116-hackathon-bgp-mup-safi-interop.html
Thank you for your kind cooperation.

**Pull request closed without merging**
