### PR TITLE
[WIP] add initial combination test cases

### PR DESCRIPTION
**Pull request by marcin-ptaszynski**
enable add-path, rtc, rr, graceful-restart at the same time
and perform integration tests.

We've experienced that sometimes combinations of features break
correct BGP behavior.

### CODE REVIEW

**Comment by marcin-ptaszynski** [comment]
Is affected by #1688

**Comment by fujita** [comment]
Can you simply add this to route_reflector_test.py?

**Comment by marcin-ptaszynski** [comment]
Thanks @fujita , I'll add them as you say to RR test-suite and expand the list. Marking as WIP for now.

**Comment by iwaseyusuke** [comment]
@marcin-ptaszynski Hi, I think the most cases (combinations of add-path, RR and GR) can be tested on `test/scenario_test/rtc_test.py` with PR https://github.com/osrg/gobgp/pull/1705. Could you check whether `test/scenario_test/rtc_test.py` covers test cases you are going to add with this PR?

**Comment by fujita** [comment]
@marcin-ptaszynski if you find something to add, please create a new pr to improve rtc_test.py.

**Pull request closed without merging**
