### PR TITLE
Add upstart init file for Ubuntu 14.04

### PR DESCRIPTION
**Pull request by pavel-odintsov**
Hello!

As discussed before I would like to share my Upstart init file for Ubuntu 14.04.

### CODE REVIEW

**Comment by fujita** [comment]
gobgpd.conf is appropriate for the name of upstart init file?

**Comment by pavel-odintsov** [comment]
Yes it is :) Full name is: /etc/init/gobgpd.conf

On Mon, Mar 14, 2016 at 5:29 AM, FUJITA Tomonori <notifications@github.com>
wrote:

> gobgpd.conf is appropriate for the name of upstart init file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osrg/gobgp/pull/763#issuecomment-196111560>.
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by fujita** [comment]
Seems that I have to catch up with upstart era. Pushed, thanks!

**Comment by pavel-odintsov** [comment]
Thanks :)

**Pull request closed without merging**
