### PR TITLE
block next hop attribute for ipv6

### PR DESCRIPTION
**Pull request by zhbngchen**

### CODE REVIEW

**Comment by fujita** [comment]
RFC says it should be blocked?

**Comment by zhbngchen** [comment]
The Multi-Protocol Reach NLRI (Type 14) attribute has next_hop in it
already.

Under the same circumstances, we tested Quagga bgpd which does not have
stand-alone next_hop and it works.

**Comment by fujita** [comment]
Unless RFC says so, I don't think that it needs to be blocked.

**Comment by fujita** [comment]
or other implementations do this?

**Pull request closed without merging**
